-- Encontrado al investigar si el respaldo diario (backup-diario) es
-- realmente restaurable: 8 de las 49 tablas que ese respaldo SÍ junta nunca
-- tuvieron un CREATE TABLE en ninguna migración — se crearon a mano en el
-- dashboard de Supabase en algún momento. Sin esto, ni siquiera se podría
-- reconstruir el ESQUEMA completo desde cero a partir del repo — un
-- requisito básico para que el respaldo sirva ante la pérdida TOTAL de un
-- proyecto Supabase (no solo corrupción de datos, donde alcanza con
-- restaurar filas sobre un esquema que ya existe).
--
-- Esquema copiado 1:1 del proyecto real (introspección read-only,
-- 2026-09-11). `if not exists` en todo: estas 8 tablas YA EXISTEN en los
-- proyectos reales (Besalco y sistema-mp2) — ahí esta migración es un
-- no-op total; solo importa para poder reproducir el esquema completo en
-- un proyecto nuevo desde cero.

-- user_roles: la tabla de autorización central (rol/activo de cada login).
create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid,
  role text,
  nombre text,
  activo boolean not null default true
);
alter table public.user_roles enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='user_roles' and policyname='usuarios ven su propio rol') then
    create policy "usuarios ven su propio rol" on public.user_roles for select to authenticated using ((select auth.uid()) = user_id);
  end if;
end $$;

-- Tablas operacionales (tren de rodaje, historiales de repuesto).
create table if not exists public.tren_rodaje (
  id text primary key default (gen_random_uuid())::text,
  sigla text not null,
  lado text not null,
  componente text not null,
  "valorNuevo" numeric,
  "limiteDesgaste" numeric,
  "valorActual" numeric,
  "pctRemanente" numeric,
  "fechaInst" date,
  "ultimaMedicion" date,
  "horomInstalacion" numeric,
  estado text default 'Operativo',
  obs text,
  created_at timestamptz not null default now()
);

create table if not exists public.tren_rodaje_mediciones (
  id uuid primary key default gen_random_uuid(),
  sigla text,
  lado text,
  componente text,
  fecha date,
  horom numeric,
  "valorMedido" numeric,
  obs text,
  created_at timestamptz not null default now()
);

create table if not exists public.historial_componentes (
  id uuid primary key default gen_random_uuid(),
  sigla text,
  comp text,
  "fechaInst" date,
  "horomInstalacion" numeric,
  fuente text,
  obs text,
  created_at timestamptz not null default now(),
  "posibleCausa" text,
  origen text
);

create table if not exists public.historial_neumaticos (
  id uuid primary key default gen_random_uuid(),
  sigla text,
  posicion text,
  fecha date,
  horom numeric,
  fuente text,
  obs text,
  created_at timestamptz not null default now()
);

alter table public.tren_rodaje enable row level security;
alter table public.tren_rodaje_mediciones enable row level security;
alter table public.historial_componentes enable row level security;
alter table public.historial_neumaticos enable row level security;

do $$
declare t text;
begin
  foreach t in array array['tren_rodaje','tren_rodaje_mediciones','historial_componentes','historial_neumaticos']
  loop
    if not exists (select 1 from pg_policies where schemaname='public' and tablename=t and policyname='operacional_select') then
      execute format('create policy "operacional_select" on public.%I for select to authenticated using (privado.es_usuario_activo())', t);
    end if;
    if not exists (select 1 from pg_policies where schemaname='public' and tablename=t and policyname='operacional_insert') then
      execute format('create policy "operacional_insert" on public.%I for insert to authenticated with check (privado.es_editor_activo())', t);
    end if;
    if not exists (select 1 from pg_policies where schemaname='public' and tablename=t and policyname='operacional_update') then
      execute format('create policy "operacional_update" on public.%I for update to authenticated using (privado.es_editor_activo()) with check (privado.es_editor_activo())', t);
    end if;
    if not exists (select 1 from pg_policies where schemaname='public' and tablename=t and policyname='operacional_delete') then
      execute format('create policy "operacional_delete" on public.%I for delete to authenticated using (privado.es_editor_activo())', t);
    end if;
  end loop;
end $$;

-- kv: mirror legado ("ya casi sin uso" según store.js), mismo patrón de RLS
-- que el resto de las tablas operacionales.
create table if not exists public.kv (
  key text primary key,
  value jsonb,
  updated_at timestamptz default now()
);
alter table public.kv enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='kv' and policyname='operacional_select') then
    create policy "operacional_select" on public.kv for select to authenticated using (privado.es_usuario_activo());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='kv' and policyname='operacional_insert') then
    create policy "operacional_insert" on public.kv for insert to authenticated with check (privado.es_editor_activo());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='kv' and policyname='operacional_update') then
    create policy "operacional_update" on public.kv for update to authenticated using (privado.es_editor_activo()) with check (privado.es_editor_activo());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='kv' and policyname='operacional_delete') then
    create policy "operacional_delete" on public.kv for delete to authenticated using (privado.es_editor_activo());
  end if;
end $$;

-- Snapshots internos de backup-diario — sin PK (son un registro histórico
-- de puntos en el tiempo acumulados, no una fila por entidad). RLS
-- habilitado pero SIN ninguna política, igual que en el proyecto real:
-- solo accesibles vía service_role, ningún usuario autenticado normal
-- puede leerlas ni escribirlas.
create table if not exists public.movimientos_stock_backup_lub (
  id uuid,
  equipo text,
  tipo text,
  item text,
  "nParte" text,
  cant numeric,
  ant numeric,
  nuevo numeric,
  fecha date,
  mes text,
  pm text,
  created_at timestamptz,
  respaldado_en timestamptz,
  item_original text
);
alter table public.movimientos_stock_backup_lub enable row level security;

create table if not exists public.stock_filtros_backup_csv (
  id uuid,
  "nParte" text,
  descripcion text,
  "equipoModelo" text,
  "stockBodega" numeric,
  "consumoMes" numeric,
  "proyMes" numeric,
  "mesesCubierto" text,
  pendiente numeric,
  comprar numeric,
  "precioUnit" numeric,
  "codAlt" text,
  estado text,
  created_at timestamptz,
  respaldado_en timestamptz
);
alter table public.stock_filtros_backup_csv enable row level security;
